languageCode = "en-us"
title        = "Keizer Internet"
baseURL      = "http://keizerinternet.com"
theme        = "black-and-light"
canonifyurls = true

[[menu.main]]
  name = "About"
  url  = "/about"
[[menu.main]]
  name = "Mission"
  url  = "/mission"
[[main.menu]]
  name = "Facebook"
  url  = "/facebook"

[params]
sitename = "Keizer Municiple Internet Project"

